- name: Install Xorg and desktop tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xev
      - xorg-xdpyinfo
      - xdg-user-dirs

- name: Install WM
  become: yes
  pacman: name=bspwm

- name: Install hotkey daemon
  become: yes
  pacman: name=sxhkd

- name: Install status bar
  yay: name=polybar

- name: Install screen utilities
  block:
    - become: yes
      pacman:
        name:
          - arandr
          - autorandr
          - maim # printscreen
          - redshift # color temperature
          - picom # compositor - transparency
    - yay: name=caffeine-ng

- name: Install locking tools
  become: yes
  pacman:
    name:
      - xss-lock
      - i3lock-color

- name: Install clipboard tools
  become: yes
  pacman:
    name:
      - xsel
      - xclip
      - autocutsel

- name: Install window management tools
  block:
    - become: yes
      pacman:
        name:
          - xorg-xwininfo
          - xorg-xkill
          - xdotool
          - wmname
          - wmctrl
    - yay: name=wmutils-git

- name: Install background tools
  become: yes
  pacman:
    name:
      - xorg-xsetroot
      - hsetroot
