- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xev
      - xorg-xwininfo
      - xsel
      - picom
      - xdg-user-dirs

- name: Install WM
  become: yes
  pacman: name=bspwm

- name: Install hotkey daemon
  become: yes
  pacman: name=sxhkd

- name: Install status bar
  yay: name=polybar

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - arandr
      - i3lock
      - scrot # Printscreen
