- name: Install Xorg and desktop tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xev
      - xorg-xwininfo
      - xsel
      - picom
      - i3lock
      - xdg-user-dirs
      - xorg-xdpyinfo
      - xorg-xsetroot
      - hsetroot
      - wmname

- name: Install WM
  become: yes
  pacman: name=bspwm

- name: Install hotkey daemon
  become: yes
  pacman: name=sxhkd

- name: Install status bar
  yay: name=polybar

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - arandr
      - autorandr
      - scrot # Printscreen
      - redshift
