- name: Install Bluetooth
  become: yes
  block:
    - name: install back-end
      pacman:
        name:
          - bluez
          - bluez-utils
          - pulseaudio-bluetooth
    - name: enable service
      systemd: name=bluetooth enabled=yes state=started
    - name: install front-end
      pacman: name=blueman
