- name: Copy etc configuration files
  become: yes
  copy: src=etc/ dest=/etc/

- name: Copy usr configuration files
  become: yes
  copy: src=usr/ dest=/usr/

- name: Download dotfiles
  git:
    repo=git@github.com:bruno-delfino1995/dotfiles.git
    dest=~/.dotfiles
    version=master
    update=yes
  become: false

- name: Install dotfiles
  shell: ~/.dotfiles/scripts/install-home
