- name: Install core packages
  become: yes
  pacman:
    name:
      - git
      - openssh
      - rsync
      - curl
      - wget
      - tree
      - htop
      - zip
      - unzip
      - man-db
      - man-pages
      - moreutils

- name: Install shell tools
  block:
    - yay: name={{ item }}
      loop:
        - direnv
        - apache-tools
        - tmuxinator
    - become: yes
      pacman:
        name:
          - fd
          - ripgrep
          - tldr
          - tmux
