- name: Install editor
  become: yes
  pacman: name=neovim

- name: Install plugins
  block:
    - name: create autoload dir
      file: path=~/.local/share/nvim/site/autoload state=directory
    - name: download vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim
    - name: install plugins
      shell: nvim +PlugInstall +qa
