- name: Install editor
  become: yes
  pacman: name=neovim

- name: Install plugins
  block:
    - file: path=~/.local/share/nvim/site/autoload state=directory
    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim
    - shell: nvim +PlugInstall +qa
