
- name: Install network manager
  become: yes
  pacman: name=netctl

- name: Install DHCP Client Daemon
  become: yes
  pacman: name=dhcpcd

- name: Install Wifi tools
  become: yes
  pacman: name=wpa_supplicant,dialog

- name: Install resolvconf for DNS config
  become: yes
  pacman: name=openresolv

- name: Install openvpn for VPN connections
  become: yes
  pacman: name=openvpn
