
- name: Install network manager
  become: yes
  pacman: name=networkmanager

- name: Install DHCP Client
  become: yes
  pacman: name=dhcpcd

- name: Install Wifi tools
  become: yes
  pacman: name=wpa_supplicant

- name: Install DNS resolver
  become: yes
  pacman: name=openresolv

- name: Install VPN tools
  become: yes
  pacman: name=openvpn,networkmanager-openvpn
