- name: Install avahi
  become: yes
  block:
    - name: install
      pacman:
        name:
          - avahi
          - nss-mdns
    - name: enable
      systemd: name=avahi-daemon enabled=yes state=started

- name: Install printing system
  become: yes
  block:
    - name: install
      pacman: name=cups
    - name: enable
      systemd: name=cups.socket enabled=yes state=started
