- name: Install ZSH
  become: yes
  pacman: name=zsh

- name: Set ZSH as user's shell
  become: yes
  shell: chsh -s /bin/zsh bruno

- name: Install Antibody
  yay: name=antibody

- name: Install ASDF
  git:
    repo=https://github.com/asdf-vm/asdf.git
    dest=~/.asdf
    version=v0.7.6

- name: Install shell tools
  block:
    - yay: name={{ item }}
      loop:
        - direnv
        - the_silver_searcher
    - become: yes
      pacman:
        name:
          - fd
