- name: Install ZSH
  become: yes
  pacman: name=zsh

- name: Install direnv
  yay: name=direnv

- name: Set ZSH as user's shell
  become: yes
  shell: chsh -s /bin/zsh bruno

- name: Install terminal
  become: yes
  pacman: name=termite

- name: Install Antibody
  yay: name=antibody

- name: Install ASDF
  git:
    repo=https://github.com/asdf-vm/asdf.git
    dest=~/.asdf
    version=v0.6.3
