- name: Install Vim
  become: yes
  pacman: name=vim

- name: Ensure autoload exists
  file: path=~/.vim/autoload state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Install vim plugins
  shell: vim -c PlugInstall -c q -c q
