- name: Install SmartCard tools
  become: yes
  block:
    - name: install
      pacman:
        name:
          - opensc
          - ccid
    - name: enable
      systemd: name=pcscd enabled=yes state=started

- name: Install Yubikey tools
  become: yes
  pacman:
    name:
      - libu2f-host
      - yubikey-manager
      - yubikey-personalization
      - yubioath-desktop

