- name: Copy configuration files
  become: yes
  copy: src=etc/ dest=/etc/

- name: Install NetworkManager
  become: yes
  pacman: name=networkmanager

- name: Enable NetworkManager
  become: yes
  systemd: name=NetworkManager enabled=yes state=started

- name: Install wireless daemon
  become: yes
  pacman: name=iwd
